name:  Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # 允许手动触发工作流
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-on-ubuntu2204:
    strategy:
      matrix:
        os: [ darwin, windows, linux ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-22.04
    name: Release on ${{ matrix.os }} ${{ matrix.arch }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name:  Build
        run: |
          make clean
          SNAPSHOT_VERSION=${{ github.ref_name }} TARGET_OS=${{ matrix.os }} TARGET_ARCH=${{ matrix.arch }} make env
          SNAPSHOT_VERSION=${{ github.ref_name }} TARGET_OS=${{ matrix.os }} TARGET_ARCH=${{ matrix.arch }} make build
          pwd
          ls -al ./bin
      - name: Create Archive
        run: |
          mkdir -p ./dist
          pwd
          ls -al ./bin
          if [ "${{ matrix.os }}" = "windows" ]; then
            cd ./bin && zip -qr ./../dist/build-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.zip ./bin/ . && cd ..
          else
            tar -czvf dist/build-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C ./bin/ .
          fi
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            ./dist/build-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.*
