name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/sup-go@v5
        with:
          go-version: '1.21.x'

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        run: |
          cd DeepseekMCP
          go build -o deepseek-mcp.exe

      - uses: softprops/action-gh-release@v1
        with:
          files: DeepseekMCP/deepseek-mcp.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
